[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "newsrag-retrieval"
version = "0.1.6"
requires-python = ">=3.9"
description = "RAG utilities for the research agent"
dependencies = ["boto3>=1.34"]

[tool.hatch.build.targets.wheel]
packages = ["newsrag_retrieval"]
