apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: newsrag
resources:
  - ../../base/newsrag-config.yaml
  - ../../base/newsrag-secrets.yaml
  - ../../base/celery-worker.yaml
  - ../../base/api.yaml
  - ../../base/cron-enqueue-feeds.yaml   # use CronJob in prod (Beat off)

# Remove in-cluster Redis; point to managed Redis via env below
# (intentionally not including ../../base/redis.yaml)

configMapGenerator:
  - name: newsrag-config
    behavior: merge
    literals:
      - STORAGE_BACKEND=s3
      - S3_BUCKET=newsrag-prod-ragdb
      - S3_PREFIX=ragdb
      - FEEDS_ENABLE=0                 # Beat disabled in prod
      - CELERY_BROKER_URL=redis://<managed-redis-host>:6379/0
      - CELERY_RESULT_BACKEND=redis://<managed-redis-host>:6379/1
      - REDIS_URL=redis://<managed-redis-host>:6379/2

# Scale Beat to 0 if it exists from base (or just omit it from resources)
patches:
  - target:
      kind: Deployment
      name: newsrag-beat
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0

# Pin prod image tags from CI (example using GHCR SHA placeholders)
images:
  - name: newsrag/api:dev
    newName: ghcr.io/yourorg/newsrag-api
    newTag: $IMAGE_TAG
  - name: newsrag/worker:dev
    newName: ghcr.io/yourorg/newsrag-worker
    newTag: $IMAGE_TAG
