[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "newsrag-api"
version = "0.1.1"
requires-python = ">=3.9"
description = "FastAPI layer for the research agent (Phase 4)"
dependencies = [
  "fastapi>=0.110",
  "uvicorn[standard]>=0.23",
]

[tool.hatch.build.targets.wheel]
packages = ["newsrag_api"]
