[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "newsrag-core"
version = "0.1.1"
requires-python = ">=3.9"
description = "Shared core for research agent phases"

[tool.hatch.build.targets.wheel]
packages = ["newsrag_core"]
