[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "newsrag-tasks"
version = "0.1.2"
requires-python = ">=3.9"
description = "Celery tasks for research agent"

[tool.hatch.build.targets.wheel]
packages = ["newsrag_tasks"]
