[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "research-tasks"
version = "0.1.1"
requires-python = ">=3.9"
description = "Celery tasks for research agent"

[tool.hatch.build.targets.wheel]
packages = ["research_tasks"]
