# k8s/base/cron-enqueue-feeds.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: newsrag-enqueue-feeds
spec:
  schedule: "0 * * * *"  # every hour on the hour
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: enqueue-feeds
              image: newsrag/worker:dev
              imagePullPolicy: IfNotPresent
              command: ["uv", "run", "python", "-m", "newsrag_tasks.enqueue_feeds"]
              envFrom:
                - configMapRef:
                    name: newsrag-config
                - secretRef:
                    name: newsrag-secret
