apiVersion: batch/v1
kind: CronJob
metadata:
  name: enqueue-feeds
  namespace: research
spec:
  schedule: "*/5 * * * *"   # every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: enqueuer
              image: research/worker:dev   # reuse worker image (has code + deps)
              envFrom:
                - configMapRef: { name: research-env }
                - secretRef:    { name: research-secrets }
              command:
                - sh
                - -lc
                - |
                  python - <<'PY'
                  import os
                  from newsrag_tasks.celery_app import app
                  corpus = os.getenv("FEEDS_CORPUS_ID","news-live")
                  app.send_task("fetch_feeds_task", args=(corpus,))
                  print("enqueued feeds for", corpus)
                  PY
