apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: research
resources:
  - ../../base/namespace.yaml
  - ../../base/configmap-env.yaml
  - ../../base/secret-env.yaml
  - ../../base/redis.yaml
  - ../../base/deploy-api.yaml
  - ../../base/deploy-worker.yaml
  - ../../base/cron-enqueue-feeds.yaml
