name: build-and-push
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tags
        id: vars
        run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build images
        run: |
          docker build -t ghcr.io/${{ github.repository }}/newsrag-api:${{ steps.vars.outputs.TAG }} -f Dockerfile.api .
          docker build -t ghcr.io/${{ github.repository }}/newsrag-worker:${{ steps.vars.outputs.TAG }} -f Dockerfile.worker .

      - name: Push images
        run: |
          docker push ghcr.io/${{ github.repository }}/newsrag-api:${{ steps.vars.outputs.TAG }}
          docker push ghcr.io/${{ github.repository }}/newsrag-worker:${{ steps.vars.outputs.TAG }}

      - name: Summary
        run: |
          echo "Pushed:" >> $GITHUB_STEP_SUMMARY
          echo "- ghcr.io/${{ github.repository }}/newsrag-api:${{ steps.vars.outputs.TAG }}" >> $GITHUB_STEP_SUMMARY
          echo "- ghcr.io/${{ github.repository }}/newsrag-worker:${{ steps.vars.outputs.TAG }}" >> $GITHUB_STEP_SUMMARY
